version: 2

jobs:
    build-and-test:
        macos:
            xcode: "9.3.0"
        # Use custom shell per https://circleci.com/docs/2.0/testing-ios/#using-custom-versions-of-cocoapods-and-other-ruby-gems
        shell: /bin/bash --login -o pipefail
        steps:
            - checkout
            - run:
                name: Run iOS Tests
                command: set -o pipefail && xcodebuild clean build test -project SweetDataSourceDemo/SweetDataSourceDemo.xcodeproj -scheme "SweetDataSourceDemo" -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty --color && exit ${PIPESTATUS[0]}
            #TODO: re-enable once we have a tvOS target
            #- run:
                #name: Run tvOS Tests
                #command: set -o pipefail && xcodebuild clean build test -project SweetDataSourceDemo.xcodeproj -scheme "tvOSTests" -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty --color && exit ${PIPESTATUS[0]}
workflows:
  version: 2
  build-and-test:
      jobs:
          - build-and-test
